# Generated by Django 5.0.7 on 2024-09-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Device_Name', models.CharField(max_length=100)),
                ('API_Key', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('Is_Active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
            },
        ),
        migrations.CreateModel(
            name='manage_validate_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OTP', models.CharField(blank=True, max_length=32)),
                ('UUID', models.UUIDField(blank=True)),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
                ('Is_Validated', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Validate Request',
                'verbose_name_plural': 'Validate Requests',
            },
        ),
    ]
